pull_request_rules:
  - name: automatic merge
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: true
    conditions:
    - label!=work-in-progress
    - '#approved-reviews-by>=1'
    - status-success=doc (docs)
    - status-success=doc (docs-gnocchi-web)

    - status-success=check (pep8)

    - status-success=test (py36-postgresql-file-upgrade-from-4.3)
    - status-success=test (py36-mysql-file)
    - status-success=test (py36-mysql-swift)
    - status-success=test (py36-mysql-s3)
    - status-success=test (py36-postgresql-file)
    - status-success=test (py36-postgresql-swift)
    - status-success=test (py36-postgresql-s3)

    - status-success=test (py38-mysql-ceph-upgrade-from-4.3)
    - status-success=test (py38-postgresql-file-upgrade-from-4.3)
    - status-success=test (py38-mysql-file)
    - status-success=test (py38-mysql-swift)
    - status-success=test (py38-mysql-s3)
    - status-success=test (py38-mysql-ceph)
    - status-success=test (py38-postgresql-file)
    - status-success=test (py38-postgresql-swift)
    - status-success=test (py38-postgresql-s3)
    - status-success=test (py38-postgresql-ceph)

  - name: automatic merge backports from Mergify
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: true
    conditions:
    - base~=^stable/.*
    - label!=work-in-progress
    - author=mergify[bot]
    - status-success=doc (docs)
    - status-success=doc (docs-gnocchi-web)

    - status-success=check (pep8)

    - status-success=test (py36-postgresql-file-upgrade-from-4.3)
    - status-success=test (py36-mysql-file)
    - status-success=test (py36-mysql-swift)
    - status-success=test (py36-mysql-s3)
    - status-success=test (py36-postgresql-file)
    - status-success=test (py36-postgresql-swift)
    - status-success=test (py36-postgresql-s3)

    - status-success=test (py38-mysql-ceph-upgrade-from-4.3)
    - status-success=test (py38-postgresql-file-upgrade-from-4.3)
    - status-success=test (py38-mysql-file)
    - status-success=test (py38-mysql-swift)
    - status-success=test (py38-mysql-s3)
    - status-success=test (py38-mysql-ceph)
    - status-success=test (py38-postgresql-file)
    - status-success=test (py38-postgresql-swift)
    - status-success=test (py38-postgresql-s3)
    - status-success=test (py38-postgresql-ceph)

  - name: dismiss reviews on additional commit
    actions:
      dismiss_reviews: {}
    conditions: []

# Backports to stable branches
  - actions:
      backport:
        branches:
        - stable/4.3
    conditions:
    - label=backport-to-4.3
    name: backport stable/4.3
  - actions:
      backport:
        branches:
        - stable/4.4
    conditions:
    - label=backport-to-4.4
    name: backport stable/4.4
