name: Gnocchi

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# NOTE(tobias-urdin): If you change any jobs make sure to modify
# the Mergify.io config in .mergify.yml to include the jobs!

jobs:
  doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - docs
          - docs-gnocchi-web
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/gnocchi-container
        with:
          command: tox -e ${{ matrix.env }}

  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - pep8
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/gnocchi-container
        with:
          command: tox -e ${{ matrix.env }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - py36
          - py38
        env:
          - mysql-ceph-upgrade-from-4.3
          - postgresql-file-upgrade-from-4.3
          - mysql-file
          - mysql-swift
          - mysql-s3
          - mysql-ceph
          - postgresql-file
          - postgresql-swift
          - postgresql-s3
          - postgresql-ceph
        exclude:
          - env: mysql-ceph-upgrade-from-4.3
            python: py36
          - env: mysql-ceph
            python: py36
          - env: postgresql-ceph
            python: py36
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/gnocchi-container
        with:
          command: tox -e ${{ matrix.python }}-${{ matrix.env }}
